PCB: true
batchsize: 16
color_jitter: false
data_dir: ../data/duke/pytorch
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids: '0'
lr: 0.05
multi: false
name: ft_ResNet50
nclasses: 702
stride: 2
test_dir: ../data/duke/pytorch
train_all: false
use_dense: false
which_epoch: last
